name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP with selected files
        run: |
          mkdir output
          zip -r output/Gini.zip src/ chroma_db/ requirements.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: output/Gini.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

